/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package egresadosapp;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.lang.model.SourceVersion;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Soporte6
 */
public final class egresados extends javax.swing.JFrame {
    
    
    conexionDB cc=new conexionDB();
    Connection con=cc.conexion();

    /**
     * Creates new form egresados
     */
    public egresados() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Egresados");
        MostrarDatos();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtape = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boxciu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblegre = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        boxcarr = new javax.swing.JComboBox<>();
        txtguar = new javax.swing.JButton();
        txtactu = new javax.swing.JButton();
        txtelim = new javax.swing.JButton();
        txtnuevo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcedu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnvolver = new javax.swing.JButton();
        txtfechanac = new javax.swing.JTextField();
        txtfechaegre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane4.setPreferredSize(new java.awt.Dimension(926, 500));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EGRESADOS");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        nom.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Telefono");

        jLabel4.setText("Edad");

        jLabel5.setText("Fecha Nacimiento");

        jLabel7.setText("Año egresado");

        jLabel8.setText("Ciudad");

        boxciu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxciu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bogota", "Medellin", "Cali", "Santa Marta", "Barranquilla", "Cucuta", "Soacha", "Manizales", "Pasto", "Rioacha", "Tunja", "Envigado", "Florencia", "Yopal", "Zipaquira", "Rionegro", " " }));
        boxciu.setToolTipText("");
        boxciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxciuActionPerformed(evt);
            }
        });

        tblegre.setBackground(new java.awt.Color(0, 0, 0));
        tblegre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblegre.setForeground(new java.awt.Color(255, 255, 255));
        tblegre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblegre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblegreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblegre);

        jLabel9.setText("Carrera");

        boxcarr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxcarr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquitectura ", "Moda", "Diseño", "Comercio", "Contaduría", "Hotelería ", "Gastronomía", "Ingeniería ", "Seguridad", "Criminología" }));

        txtguar.setText("Guardar");
        txtguar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtguarActionPerformed(evt);
            }
        });

        txtactu.setText("Actualizar");
        txtactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactuActionPerformed(evt);
            }
        });

        txtelim.setText("Eliminar");
        txtelim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtelimActionPerformed(evt);
            }
        });

        txtnuevo.setText("Nuevo Registro");
        txtnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuevoActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar");

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        jLabel11.setText("Cedula");

        jLabel12.setText("Correo");

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        jDesktopPane4.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(nom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtnom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtape, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txttel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtedad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(boxciu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(boxcarr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtguar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtactu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtelim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtnuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtbuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtcedu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtcorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(btnvolver, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtfechanac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtfechaegre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(382, 382, 382))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                                .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnuevo)
                .addGap(18, 18, 18)
                .addComponent(txtactu)
                .addGap(18, 18, 18)
                .addComponent(txtguar)
                .addGap(18, 18, 18)
                .addComponent(txtelim)
                .addGap(253, 253, 253)
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcedu, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                            .addComponent(txtnom)))
                                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxciu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)
                                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))))
                        .addGap(28, 28, 28)
                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxcarr, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtedad, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(txtfechanac)
                    .addComponent(txtfechaegre))
                .addGap(42, 42, 42))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtcedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(boxcarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechaegre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxciu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtelim)
                    .addComponent(txtguar)
                    .addComponent(txtactu)
                    .addComponent(txtnuevo))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxciuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxciuActionPerformed

    private void txtnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuevoActionPerformed
        LimpiarDatos();
    }//GEN-LAST:event_txtnuevoActionPerformed

    private void txtactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactuActionPerformed
       ActualizarDatos();
       LimpiarDatos();
       MostrarDatos();
    }//GEN-LAST:event_txtactuActionPerformed
        
    private void txtguarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtguarActionPerformed
       InsertarDatos();
       LimpiarDatos();
       MostrarDatos();
    }//GEN-LAST:event_txtguarActionPerformed

    private void txtelimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtelimActionPerformed
        EliminarDatos();
        MostrarDatos();
        LimpiarDatos();
    }//GEN-LAST:event_txtelimActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        LimpiarDatos();
        BuscarDatos(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void tblegreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblegreMouseClicked
        int filaSelec=tblegre.rowAtPoint(evt.getPoint());
        
        txtcedu.setText(tblegre.getValueAt(filaSelec,0).toString());
        txtnom.setText(tblegre.getValueAt(filaSelec,1).toString());
        txtape.setText(tblegre.getValueAt(filaSelec,2).toString());
        txttel.setText(tblegre.getValueAt(filaSelec,3).toString());
        txtedad.setText(tblegre.getValueAt(filaSelec,4).toString());
        txtcorreo.setText(tblegre.getValueAt(filaSelec,5).toString());
        txtfechanac.setText(tblegre.getValueAt(filaSelec,6).toString());
        txtfechaegre.setText(tblegre.getValueAt(filaSelec,7).toString());
        boxcarr.setSelectedItem(tblegre.getValueAt(filaSelec,8).toString());
        boxciu.setSelectedItem(tblegre.getValueAt(filaSelec,9).toString());
        
    }//GEN-LAST:event_tblegreMouseClicked

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        menu obj=new menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

      public void BuscarDatos(String valor){
    
        String[] titulos= {"CEDULA","NOMBRE","APELLIDO","TELEFONO","EDAD","CORREO","FECHA NAC","FECHA EGRE","CARRERA","CIUDAD"};
        String[] registros=new String[10];
        
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String SQL= "select * from egresados where cedula like '%"+valor+"%' or nombre like '%"+valor+"%' "
                + "or apellido like '%"+valor+"%' or telefono like '%"+valor+"%'or edad like '%"+valor+"%'"
                + "or correo like '%"+valor+"%' or fech_nacimiento like '%"+valor+"%' or fecha_egresado like '%"+valor+"%"
                + "'or nom_titulo_aca like '%"+valor+"%' or ciudad like '%"+valor+"%' ";
        
        try {
            
            Statement  st= con.createStatement();
            ResultSet  rs=st.executeQuery(SQL);
            
            while (rs.next()){
                    
                registros[0]=rs.getString("cedula");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apellido");
                registros[3]=rs.getString("telefono");
                registros[4]=rs.getString("edad");
                registros[5]=rs.getString("correo");
                registros[6]=rs.getString("fech_nacimiento");
                registros[7]=rs.getString("fecha_egresados");
                registros[8]=rs.getString("nom_titulo_aca");
                registros[9]=rs.getString("ciudad");

                
                
                modelo.addRow(registros);
            }
            tblegre.setModel(modelo);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error Consulta" + e.getMessage());
        }
        
    }//Fin Buscar datos  
    
//Eliminar datos de la base de datos 
    public void EliminarDatos(){
    
        int filaSelec=tblegre.getSelectedRow();
        
        try {
            String SQL="delete from egresados where cedula="+tblegre.getValueAt(filaSelec,0);
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>=0){
            
              JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar registro" + e.getMessage());
        }
    }//Fin Eliminar datos 
    
//Mostrar los datos de la base de datos
    public void MostrarDatos(){
    
        String[] titulos= {"CEDULA","NOMBRE","APELLIDO","TELEFONO","EDAD","CORREO","FECHA NAC","FECHA EGRE","CARRERA","CIUDAD"};
        String[] registros=new String[10];
        
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String SQL= "select * from egresados";
        
        try {
            
            Statement  st= con.createStatement();
            ResultSet  rs=st.executeQuery(SQL);
            
            while (rs.next()){
                    
                registros[0]=rs.getString("cedula");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apellido");
                registros[3]=rs.getString("telefono");
                registros[4]=rs.getString("edad");
                registros[5]=rs.getString("correo");
                registros[6]=rs.getString("fech_nacimiento");
                registros[7]=rs.getString("fecha_egresado");
                registros[8]=rs.getString("nom_titulo_aca");
                registros[9]=rs.getString("ciudad");
                
                
                modelo.addRow(registros);
            }
            tblegre.setModel(modelo);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error Consulta" + e.getMessage());
        }
        
    }//Fin Mostrar datos
    
    
    
//Limpiar datos de la base de datos
    public void LimpiarDatos(){
        
        txtcedu.setText("");
        txtnom.setText("");
        txtape.setText("");
        txttel.setText("");
        txtedad.setText("");
        txtcorreo.setText("");
        txtfechanac.setText("");
        txtfechaegre.setText("");
        boxcarr.setSelectedItem(null);
        boxciu.setSelectedItem(null);
        
    }//Fin Limpiar Datos

//Insertar datos en la base de datos
    
    
    public void InsertarDatos(){
 
        try {
            
            String SQL="Insert into egresados(cedula,nombre,apellido,telefono,edad,correo,fech_nacimiento,"
                    + "fecha_egresado,nom_titulo_aca,ciudad) values(?,?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement pst=con.prepareStatement(SQL);
            
            
                        
            
            pst.setInt(1, Integer.parseInt(txtcedu.getText()));
            
            pst.setString(2, txtnom.getText());
            pst.setString(3, txtape.getText());
            pst.setString(4, txttel.getText());
            pst.setString(5, txtedad.getText());
            pst.setString(6, txtcorreo.getText());
            pst.setString(7, txtfechanac.getText());
            pst.setString(8, txtfechaegre.getText());    
            
            int selecciona=boxcarr.getSelectedIndex();
            pst.setString(9, boxcarr.getItemAt(selecciona));
            
            int seleccionado=boxciu.getSelectedIndex();
            pst.setString(10, boxciu.getItemAt(seleccionado)); 
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Registro" + e.getMessage());           
        }
    }//Fin Insertar Datos
    
//Actualizar Datos en la base de datos   
     public void ActualizarDatos(){
        try {
            
            String SQL="update egresados set cedula=?, nombre=?, apellido=?, telefono=?, edad=?, correo=?,"
                    + "fech_nacimiento=?, fecha_egresado=?, nom_titulo_aca=?, ciudad=? where cedula=?";
            
            int filaSelec=tblegre.getSelectedRow(); 
            String fila=(String)tblegre.getValueAt(filaSelec,0);
            PreparedStatement pst=con.prepareStatement(SQL);
            
            
            pst.setString(1, txtcedu.getText());
            pst.setString(2, txtnom.getText());
            pst.setString(3, txtape.getText());
            pst.setString(4, txttel.getText());
            pst.setString(5, txtedad.getText());
            pst.setString(6, txtcorreo.getText());
            pst.setString(7, txtfechanac.getText());
            pst.setString(8, txtfechaegre.getText());    
            
            int selecciona=boxcarr.getSelectedIndex();
            pst.setString(9, boxcarr.getItemAt(selecciona));
            
            int seleccionado=boxciu.getSelectedIndex();
            pst.setString(10, boxciu.getItemAt(seleccionado)); 
            pst.setString(11, fila);   
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro actualizado exitosamente");
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la actualización" + e.getMessage());           
        }
    }//Fin Actuzalizar datos  
    /**
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(egresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(egresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(egresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(egresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new egresados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxcarr;
    private javax.swing.JComboBox<String> boxciu;
    private javax.swing.JButton btnvolver;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nom;
    private javax.swing.JTable tblegre;
    private javax.swing.JButton txtactu;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcedu;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtedad;
    private javax.swing.JButton txtelim;
    private javax.swing.JTextField txtfechaegre;
    private javax.swing.JTextField txtfechanac;
    private javax.swing.JButton txtguar;
    private javax.swing.JTextField txtnom;
    private javax.swing.JButton txtnuevo;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
